# based on https://github.com/dperson/samba/blob/master/docker-compose.yml
version: '3.4'

networks:
  default:

services:
  samba:
    container_name: samba
    image: dperson/samba
    restart: always
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=America/Los_Angeles
      - UMASK_SET=022
    networks:
      - default
    ports:
      - 137:137/udp
      - 138:138/udp
      - 139:139/tcp
      - 445:445/tcp
    # read_only: true
    tmpfs:
      - /tmp
    stdin_open: true
    tty: true
    volumes:
      - /storage:/storage:z
    command: '-s "Storage;/storage;yes;yes;yes"'
