# based on https://github.com/dperson/samba/blob/master/docker-compose.yml
version: '3.4'

networks:
  proxy:
    external: true

services:
  samba:
    container_name: samba
    image: dperson/samba
    restart: unless-stopped
    environment:
      - USERID=1002
      - GROUPID=998
      - TZ=America/Los_Angeles
    networks:
      - proxy
    ports:
      - 137:137/udp
      - 138:138/udp
      - 139:139/tcp
      - 445:445/tcp
    # read_only: true
    tmpfs:
      - /tmp
    stdin_open: true
    tty: true
    volumes:
      - /storage:/storage:z
    command: '-s "Storage;/storage;yes;no;yes"'
