version: '3'

networks:
  proxy:
    external: true

services:
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - PUID=1002
      - PGID=998
      - TZ=America/Los_Angeles
      - UMASK_SET=022
    ports:
      - 8989:8989
    volumes:
      - /srv/qsh/sonarr/config:/config
      - /storage/__Unsorted__:/downloads:z
      - /storage/TV:/tv:z
