version: '3'

networks:
  proxy:
    external: true

services:
  go-auto-yt:
    container_name: go-auto-yt
    image: xiovv/go-auto-yt:stable
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - PUID=1002
      - PGID=998
      - TZ=America/Los_Angeles
      - UMASK_SET=022
    ports:
      - 8002:8080
    volumes:
      - /srv/qsh/go-auto-yt/config:/app/config
      - /storage/YouTube:/app/downloads
