version: '3'

networks:
  proxy:
    external: true

services:
  trilium:
    container_name: trilium
    image: zadam/trilium
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - PUID=1002
      - PGID=998
      - TZ=America/Los_Angeles
      - UMASK_SET=022
      - TRILIUM_DATA_DIR=/data
    ports:
      - 8881:8080
    volumes:
      - /srv/qsh/trillium:/data
