version: '3'

networks:
  proxy:
    external: true

services:
  heimdall:
    container_name: heimdall
    image: linuxserver/heimdall
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - PUID=1002
      - PGID=998
      - TZ=America/Los_Angeles
      - UMASK_SET=022
    ports:
      # move ports by +10 because proxy uses that ports
      - 90:80
      - 453:443
    volumes:
      - /srv/qsh/heimdall/config:/config
