version: '3'

networks:
  proxy:
    external: true

services:
  heimdall:
    container_name: heimdall
    image: linuxserver/heimdall
    restart: always
    networks:
      - proxy
    environment:
      - PUID=1002
      - PGID=998
      - TZ=America/Los_Angeles
      - UMASK_SET=022
    ports:
      - 80:80
      - 443:443
    volumes:
      - /srv/qsh/heimdall/config:/config
