version: '3'

networks:
  proxy:
    external: true

services:
  airsonic:
    container_name: airsonic
    image: linuxserver/airsonic
    restart: always
    networks:
      - proxy
    environment:
      - PUID=1002
      - PGID=998
      - TZ=America/Los_Angeles
      - UMASK_SET=022
      # - CONTEXT_PATH=URL_BASE #optional
      # - JAVA_OPTS=options #optional
    ports:
      - 4040:4040
    volumes:
      - /srv/qsh/airsonic/config:/config
      - /storage/Music:/music:z
      - /storage/Playlists:/playlists:z
      - /storage/Podcasts:/podcasts:z
      # - /path/to/other media:/media #optiona
