version: '3'

networks:
  proxy:
    external: true
#   internal:
#     external: false

services:
  # whoami:
  #   # A container that exposes an API to show its IP address
  #   container_name: whoami
  #   image: containous/whoami
  #   labels:
  #     - traefik.enable=true
  #     - "traefik.http.routers.whoami.rule=Host(`whoami.home.qsh.ai`)"

  traefik:
    container_name: traefik
    image: traefik:v2.0
    restart: unless-stopped
    # network_mode: host
    networks:
      - proxy
    #   - internal
    # command: --web --docker --docker.domain=home.qsh.io --logLevel=DEBUG
    command:
      # - --entrypoints.web.address=:80
      - --providers.docker
      # - --api.dashboard=true
      - --api.insecure=true # Don't do that in production
    # labels:
    #   - "traefik.http.routers.traefik.rule=Host(`monitor.home.qsh.ai`)"
      # - traefik.frontend.rule=Host:monitor.home.qsh.ai
      # - traefik.docker.network=proxy
      # - traefik.port=8080
      # - traefik.enable=true
    environment:
      - PUID=1002
      - PGID=998
      - TZ=America/Los_Angeles
      - UMASK_SET=022
    ports:
      - 80:80
      # - 443:443
      - 8080:8080
    volumes:
      # - ./traefik.toml:/etc/traefik/traefik.toml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
