version: '3'

networks:
  proxy:
    external: true
  internal:
    external: false

services:
  whoami:
    # A container that exposes an API to show its IP address
    container_name: whoami
    image: containous/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"

  traefik:
    container_name: traefik
    image: traefik
    restart: unless-stopped
    networks:
      - proxy
      - internal
    # command: --web --docker --docker.domain=home.qsh.io --logLevel=DEBUG
    command: --api.insecure=true --providers.docker
    labels:
      - traefik.backend=portainer
      - traefik.frontend.rule=Host:monitor.home.qsh.ai
      - traefik.docker.network=proxy
      - traefik.port=8080
    environment:
      - PUID=1002
      - PGID=998
      - TZ=America/Los_Angeles
      - UMASK_SET=022
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ./traefik.toml:/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
