version: '3'

networks:
  proxy:
    external: true

services:
  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.00'
    networks:
      - proxy
    environment:
      - PUID=1002
      - PGID=998
      - TZ=America/Los_Angeles
      - UMASK_SET=022
    ports:
      - 7878:7878
    volumes:
      - /srv/qsh/radarr/config:/config
      - /storage/__Unsorted__:/downloads:z
      - /storage/__Unsorted__:/completed:z
      - /storage/Movies:/movies:z
      - /storage/Anime:/anime:z
