version: '3'

networks:
  proxy:
    external: true

services:
  couchpotato:
    container_name: couchpotato
    image: linuxserver/couchpotato
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - PUID=1002
      - PGID=998
      - TZ=America/Los_Angeles
      - UMASK_SET=022
    ports:
      - 5050:5050
    volumes:
      - /srv/qsh/couchpotato/config:/config
      - /storage/__Unsorted__:/downloads:z
      - /storage/__Incomplete.couchpotato__:/incomplete:z
      - /storage/Movies:/movies:z
