version: '3'

networks:
  proxy:
    external: true

services:
  hydra2:
    container_name: hydra2
    image: linuxserver/hydra2
    restart: unless-stopped
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1.00'
    networks:
      - proxy
    environment:
      - PUID=1002
      - PGID=998
      - TZ=America/Los_Angeles
      - UMASK_SET=022
    ports:
      - 5076:5076
    volumes:
      - /srv/qsh/hydra2/config:/config
      - /storage/.nzbfiles:/downloads:z
