version: '3'

networks:
  proxy:
    external: true

services:
  mylar:
    container_name: mylar
    image: linuxserver/mylar
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - PUID=1002
      - PGID=998
      - TZ=America/Los_Angeles
      - UMASK_SET=022
    ports:
      - 8091:8090
    volumes:
      - /srv/qsh/mylar/config:/config
      - /storage/__Unsorted__:/downloads:z
      - /storage/__Unsorted__:/completed:z
      - /storage/Comics:/comics:z
