version: "3"

services:
  app:
    container_name: proxy_app
    image: jc21/nginx-proxy-manager:latest
    restart: always
    environment:
      - PUID=1002
      - PGID=998
      - TZ=America/Los_Angeles
      - UMASK_SET=022
      # if you want pretty colors in your docker logs:
      - FORCE_COLOR=1
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ./config.json:/app/config/production.json
      - /srv/qsh/nginx-proxy-manager/data:/data
      - /srv/qsh/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    depends_on:
      - db

  db:
    container_name: proxy_db
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "npm"
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "npm"
      MYSQL_PASSWORD: "npm"
    volumes:
      - ./data/mysql:/var/lib/mysql
