version: "3"

networks:
  proxy:
    external: true

services:
  app:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    networks:
      - proxy
    environment:
      - PUID=1002
      - PGID=998
      - TZ=America/Los_Angeles
      - UMASK_SET=022
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ./config.json:/app/config/production.json
      - /srv/qsh/nginx-proxy-manager/data:/data
      - /srv/qsh/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    depends_on:
      - db
    environment:
    # if you want pretty colors in your docker logs:
    - FORCE_COLOR=1

  db:
    image: mariadb:latest
    restart: always
    networks:
      - proxy
    environment:
      MYSQL_ROOT_PASSWORD: "npm"
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "npm"
      MYSQL_PASSWORD: "npm"
    volumes:
      - ./data/mysql:/var/lib/mysql
