version: '3'

networks:
  proxy:
    external: true

services:
  nzbget:
    container_name: nzbget
    image: linuxserver/nzbget
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - PUID=1002
      - PGID=998
      - TZ=America/Los_Angeles
      - UMASK_SET=022
    ports:
      - 6789:6789
    volumes:
      - /srv/qsh/nzbget/config:/config
      - /storage/__Unsorted__:/downloads:z
      - /storage/_Incomplete.nzbget:/incomplete:z
