version: '3'

networks:
  proxy:
    external: true

services:
  nzbget:
    container_name: nzbget
    image: linuxserver/nzbget
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - PUID=1002
      - PGID=998
      - TZ=America/Los_Angeles
      - UMASK_SET=022
    ports:
      - 6789:6789
    volumes:
      - /srv/qsh/nzbget/config:/config
      #destdir main/completed
      - /storage/__Unsorted__:/downloads:z
      #maindir /downloads
      - /storage/.nzbget:/nzbget:z
      #interdir main/intermediate
      #nzbdir main/nzb
      #queue main/queue
      #temp main/tmp
