version: '3'

networks:
  proxy:
    external: true
  internal:
    external: false

services:
  nzbget:
    container_name: nzbget
    image: linuxserver/nzbget
    restart: unless-stopped
    networks:
      - proxy
      - internal
    labels:
      - traefik.backend=nzbget
      - traefik.frontend.rule=Host:nzbget.home.qsh.ai
      - traefik.docker.network=proxy
      - traefik.port=80
    environment:
      - PUID=1002
      - PGID=998
      - TZ=America/Los_Angeles
      - UMASK_SET=022
    ports:
      - 6789:6789
    volumes:
      - /srv/qsh/nzbget/config:/config
      - /storage/__Unsorted__:/downloads:z
      - /storage/_Incomplete.nzbget:/incomplete:z
