version: '3'

networks:
  proxy:
    external: true

services:
  organizr:
    container_name: organizr
    image: organizrtools/organizr-v2
    restart: always
    networks:
      - proxy
    environment:
      - PUID=1003
      - PGID=998
      - TZ=America/Los_Angeles
      - UMASK_SET=022
    ports:
      - 80:80
    volumes:
      - /srv/qsh/organizr/config:/config
