version: '3'

networks:
  proxy:
    external: true

services:
  jellyfin:
    container_name: jellyfin
    image: linuxserver/jellyfin
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - PUID=1002
      - PGID=998
      - TZ=America/Los_Angeles
      - UMASK_SET=022
    ports:
      - 8096:8096
      - 8920:8920 #optional
    volumes:
      - /srv/qsh/jellyfin/config:/config
      - /storage/__Unsorted__:/downloads:z
      - /storage/Movies:/movies:z
      - /storage/TV:/tv:z
      - /storage/Anime:/anime:z
      # - /path for transcoding:/transcode #optional
