version: '3'

networks:
  proxy:
    external: true
#   internal:
#     external: false

services:
  portainer:
    container_name: portainer
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    networks:
      - proxy
    #   - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.home.qsh.ai`)"
      - "traefik.http.services.portainer.loadbalancer.server.port=80"
    environment:
      - PUID=1002
      - PGID=998
      - TZ=America/Los_Angeles
      - UMASK_SET=022
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/qsh/portainer/data:/data
