version: '3'

networks:
  proxy:
    external: true

services:
  portainer:
    container_name: portainer
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    networks:
      - proxy
    environment:
      - PUID="${DOCKERUID}"
      - PGID="${DOCKERGID}"
      - TZ=America/Los_Angeles
      - UMASK_SET=022
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/qsh/portainer/data:/data
