version: '3'

networks:
  proxy:
    external: true

services:
  netdata:
    container_name: netdata
    image: netdata/netdata
    restart: always
    networks:
      - proxy
    environment:
      - PUID=1003
      - PGID=998
      - TZ=America/Los_Angeles
      - UMASK_SET=022
    # hostname: example.com # set to fqdn of host
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
