version: '3'

networks:
  proxy:
    external: true

services:
  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr
    restart: unless-stopped
    # deploy:
    #   resources:
    #     limits:
    #       cpus: 0.5
    networks:
      - proxy
    environment:
      - PUID=1002
      - PGID=998
      - TZ=America/Los_Angeles
      - UMASK_SET=022
    ports:
      - 6767:6767
    volumes:
      - /srv/qsh/bazarr/config:/config
      - /storage/Movies:/movies:z
      - /storage/TV:/tv:z
      - /storage/Anime:/anime:z
