version: '3'

networks:
  proxy:
    external: true

services:
  lidarr:
    container_name: lidarr
    image: linuxserver/lidarr
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.00'
    networks:
      - proxy
    environment:
      - PUID=1002
      - PGID=998
      - TZ=America/Los_Angeles
      - UMASK_SET=022
    ports:
      - 8686:8686
    volumes:
      - /srv/qsh/lidarr/config:/config
      - /storage/__Unsorted__:/downloads:z
      - /storage/__Unsorted__:/completed:z
      - /storage/Music:/music:z
