version: '3'

networks:
  proxy:
    external: true

services:
  syncthing:
    container_name: syncthing
    image: linuxserver/syncthing
    restart: unless-stopped
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1.00'
    networks:
      - proxy
    environment:
      - PUID=1002
      - PGID=998
      - TZ=America/Los_Angeles
      - UMASK_SET=022
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp
    volumes:
      - /srv/qsh/syncthing/config:/config
      - /usr/share/hassio:/hassio
      - /storage:/storage:z
