version: '3'

networks:
  proxy:
    external: true

services:
  cloudcmd:
    container_name: cloudcmd
    image: coderaiser/cloudcmd
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - PUID=1002
      - PGID=998
      - TZ=America/Los_Angeles
      - UMASK_SET=022
    ports:
      - 8001:8000
    volumes:
      - /srv/qsh/cloudcmd/root:/root
      - /:/mnt/fs
