version: '3.6'

networks:
  proxy:
    external: true

services:
  organizr:
    container_name: organizr
    image: organizrtools/organizr-v2
    restart: always
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - UMASK_SET=022
    ports:
      - 80:80
    volumes:
      - /srv/qsh/organizr/config:/config
