version: '3'

networks:
  proxy:
    external: true

services:
  sickchill:
    container_name: sickchill
    image: linuxserver/sickchill
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - PUID=1002
      - PGID=998
      - TZ=America/Los_Angeles
      - UMASK_SET=022
    ports:
      - 8081:8081
    volumes:
      - /srv/qsh/sickchill/config:/config
      - /storage/__Unsorted__:/downloads:z
      - /storage/TV:/tv:z
